export const MockRestaurants = [
  {
    info: {
      id: "548363",
      name: "Grill Master",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/17/6def0f0f-9e6c-45c0-b5e6-05af750f27b5_795906.JPG",
      locality: "MG Road",
      areaName: "Central District",
      costForTwo: "₹550 for two",
      cuisines: ["BBQ", "Continental", "Kebabs"],
      avgRating: 3.9,
      avgRatingString: "3.9",
      totalRatingsString: "25K+ ratings",
      veg: false,
      sla: { deliveryTime: 22, lastMileTravel: 3.8, slaString: "22 mins" },
      aggregatedDiscountInfoV3: { header: "10% OFF", subHeader: "UPTO ₹40" },
    },
  },
  {
    info: {
      id: "123658",
      name: "Frozen Yogurt Bar",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/acfcaacc-edf0-4189-8264-d614d312c0ee_740457.JPG",
      locality: "Park Street",
      areaName: "Downtown",
      costForTwo: "₹700 for two",
      cuisines: ["Desserts", "Ice Cream", "Healthy Food"],
      avgRating: 4.8,
      avgRatingString: "4.8",
      totalRatingsString: "14K+ ratings",
      veg: true,
      sla: { deliveryTime: 46, lastMileTravel: 2.4, slaString: "46 mins" },
      aggregatedDiscountInfoV3: { header: "15% OFF", subHeader: "UPTO ₹150" },
    },
  },
  {
    info: {
      id: "517406",
      name: "Momo Magic",
      cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
      locality: "Residency Road",
      areaName: "South Zone",
      costForTwo: "₹800 for two",
      cuisines: ["Tibetan", "Momos", "Street Food"],
      avgRating: 4.7,
      avgRatingString: "4.7",
      totalRatingsString: "15K+ ratings",
      veg: false,
      sla: { deliveryTime: 21, lastMileTravel: 3.3, slaString: "21 mins" },
      aggregatedDiscountInfoV3: { header: "55% OFF", subHeader: "UPTO ₹110" },
    },
  },
  {
    info: {
      id: "830015",
      name: "Firewood Pizza",
      cloudinaryImageId: "rng/md/carousel/production/indian101",
      locality: "Brigade Road",
      areaName: "City Center",
      costForTwo: "₹550 for two",
      cuisines: ["Pizza", "Italian", "Continental"],
      avgRating: 4.9,
      avgRatingString: "4.9",
      totalRatingsString: "5K+ ratings",
      veg: false,
      sla: { deliveryTime: 19, lastMileTravel: 4.8, slaString: "19 mins" },
      aggregatedDiscountInfoV3: { header: "60% OFF", subHeader: "UPTO ₹120" },
    },
  },
  {
    info: {
      id: "507409",
      name: "The Curry Leaf",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/ba9f1f59-30d5-44de-afad-df6db8471ead_9648.jpg",
      locality: "Commercial Street",
      areaName: "East District",
      costForTwo: "₹500 for two",
      cuisines: ["Kerala", "South Indian", "Seafood"],
      avgRating: 4.7,
      avgRatingString: "4.7",
      totalRatingsString: "6K+ ratings",
      veg: false,
      sla: { deliveryTime: 40, lastMileTravel: 5.0, slaString: "40 mins" },
      aggregatedDiscountInfoV3: { header: "40% OFF", subHeader: "UPTO ₹80" },
    },
  },
  {
    info: {
      id: "580416",
      name: "The Juice Junction",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/8/731001f1-f1c4-4f5f-849f-79a697cb0b72_390173.jpg",
      locality: "Lavelle Road",
      areaName: "West End",
      costForTwo: "₹350 for two",
      cuisines: ["Beverages", "Healthy Food", "Snacks"],
      avgRating: 4.8,
      avgRatingString: "4.8",
      totalRatingsString: "14K+ ratings",
      veg: true,
      sla: { deliveryTime: 44, lastMileTravel: 5.2, slaString: "44 mins" },
      aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
    },
  },
  {
    info: {
      id: "563594",
      name: "Noodle House",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/acfcaacc-edf0-4189-8264-d614d312c0ee_740457.JPG",
      locality: "Indiranagar",
      areaName: "Uptown",
      costForTwo: "₹350 for two",
      cuisines: ["Chinese", "Asian", "Noodles"],
      avgRating: 4.2,
      avgRatingString: "4.2",
      totalRatingsString: "15K+ ratings",
      veg: false,
      sla: { deliveryTime: 30, lastMileTravel: 5.2, slaString: "30 mins" },
      aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹75" },
    },
  },
  {
    info: {
      id: "383583",
      name: "The Waffle Co",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/17/6def0f0f-9e6c-45c0-b5e6-05af750f27b5_795906.JPG",
      locality: "Jayanagar",
      areaName: "South Bangalore",
      costForTwo: "₹200 for two",
      cuisines: ["Desserts", "Waffles", "Cafe"],
      avgRating: 4.8,
      avgRatingString: "4.8",
      totalRatingsString: "8K+ ratings",
      veg: true,
      sla: { deliveryTime: 23, lastMileTravel: 2.3, slaString: "23 mins" },
      aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
    },
  },
  {
    info: {
      id: "942718",
      name: "Rajasthani Rasoi",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/17/7bd350a8-55e7-459b-83a2-e250e670d194_14558.JPG",
      locality: "Koramangala",
      areaName: "Tech Hub",
      costForTwo: "₹300 for two",
      cuisines: ["Rajasthani", "Indian", "Thali"],
      avgRating: 3.9,
      avgRatingString: "3.9",
      totalRatingsString: "14K+ ratings",
      veg: true,
      sla: { deliveryTime: 36, lastMileTravel: 3.2, slaString: "36 mins" },
      aggregatedDiscountInfoV3: { header: "55% OFF", subHeader: "UPTO ₹110" },
    },
  },
  {
    info: {
      id: "481829",
      name: "Pancake House",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/17/6def0f0f-9e6c-45c0-b5e6-05af750f27b5_795906.JPG",
      locality: "Whitefield",
      areaName: "North Zone",
      costForTwo: "₹150 for two",
      cuisines: ["Breakfast", "Desserts", "Cafe"],
      avgRating: 4.2,
      avgRatingString: "4.2",
      totalRatingsString: "11K+ ratings",
      veg: false,
      sla: { deliveryTime: 47, lastMileTravel: 1.9, slaString: "47 mins" },
      aggregatedDiscountInfoV3: { header: "60% OFF", subHeader: "UPTO ₹120" },
    },
  },
  {
    info: {
      id: "966552",
      name: "The Falafel Spot",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/acfcaacc-edf0-4189-8264-d614d312c0ee_740457.JPG",
      locality: "HSR Layout",
      areaName: "Old City",
      costForTwo: "₹800 for two",
      cuisines: ["Lebanese", "Mediterranean", "Healthy Food"],
      avgRating: 4.6,
      avgRatingString: "4.6",
      totalRatingsString: "3K+ ratings",
      veg: true,
      sla: { deliveryTime: 50, lastMileTravel: 1.7, slaString: "50 mins" },
      aggregatedDiscountInfoV3: { header: "45% OFF", subHeader: "UPTO ₹90" },
    },
  },
  {
    info: {
      id: "609396",
      name: "Lucknowi Dastarkhan",
      cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
      locality: "Electronic City",
      areaName: "New Town",
      costForTwo: "₹350 for two",
      cuisines: ["Awadhi", "North Indian", "Kebabs"],
      avgRating: 3.7,
      avgRatingString: "3.7",
      totalRatingsString: "4K+ ratings",
      veg: false,
      sla: { deliveryTime: 37, lastMileTravel: 4.1, slaString: "37 mins" },
      aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹75" },
    },
  },
  {
    info: {
      id: "431431",
      name: "The Salad Bar",
      cloudinaryImageId: "rng/md/carousel/production/indian101",
      locality: "Malleshwaram",
      areaName: "Suburban Belt",
      costForTwo: "₹500 for two",
      cuisines: ["Healthy Food", "Salads", "Vegan"],
      avgRating: 4.2,
      avgRatingString: "4.2",
      totalRatingsString: "15K+ ratings",
      veg: true,
      sla: { deliveryTime: 46, lastMileTravel: 3.0, slaString: "46 mins" },
      aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹75" },
    },
  },
  {
    info: {
      id: "609162",
      name: "Pasta Palace",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/ba9f1f59-30d5-44de-afad-df6db8471ead_9648.jpg",
      locality: "Basavanagudi",
      areaName: "Metro Corridor",
      costForTwo: "₹800 for two",
      cuisines: ["Italian", "Pasta", "Continental"],
      avgRating: 4.5,
      avgRatingString: "4.5",
      totalRatingsString: "12K+ ratings",
      veg: true,
      sla: { deliveryTime: 44, lastMileTravel: 3.3, slaString: "44 mins" },
      aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹75" },
    },
  },
  {
    info: {
      id: "820112",
      name: "Pizza Paradise",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/8/731001f1-f1c4-4f5f-849f-79a697cb0b72_390173.jpg",
      locality: "Rajajinagar",
      areaName: "Riverside",
      costForTwo: "₹400 for two",
      cuisines: ["Pizza", "Italian", "Fast Food"],
      avgRating: 4.9,
      avgRatingString: "4.9",
      totalRatingsString: "7K+ ratings",
      veg: false,
      sla: { deliveryTime: 21, lastMileTravel: 3.5, slaString: "21 mins" },
      aggregatedDiscountInfoV3: { header: "10% OFF", subHeader: "UPTO ₹40" },
    },
  },
  {
    info: {
      id: "832516",
      name: "Punjab Da Dhaba",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/acfcaacc-edf0-4189-8264-d614d312c0ee_740457.JPG",
      locality: "Marathahalli",
      areaName: "Central District",
      costForTwo: "₹700 for two",
      cuisines: ["Punjabi", "North Indian", "Tandoor"],
      avgRating: 4.0,
      avgRatingString: "4.0",
      totalRatingsString: "16K+ ratings",
      veg: false,
      sla: { deliveryTime: 37, lastMileTravel: 5.8, slaString: "37 mins" },
      aggregatedDiscountInfoV3: { header: "55% OFF", subHeader: "UPTO ₹110" },
    },
  },
  {
    info: {
      id: "342020",
      name: "Thai Terrace",
      cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
      locality: "BTM Layout",
      areaName: "Downtown",
      costForTwo: "₹300 for two",
      cuisines: ["Thai", "Asian", "Curries"],
      avgRating: 4.6,
      avgRatingString: "4.6",
      totalRatingsString: "9K+ ratings",
      veg: false,
      sla: { deliveryTime: 49, lastMileTravel: 5.8, slaString: "49 mins" },
      aggregatedDiscountInfoV3: { header: "60% OFF", subHeader: "UPTO ₹120" },
    },
  },
  {
    info: {
      id: "498594",
      name: "Wok This Way",
      cloudinaryImageId: "rng/md/carousel/production/indian101",
      locality: "JP Nagar",
      areaName: "South Zone",
      costForTwo: "₹200 for two",
      cuisines: ["Chinese", "Thai", "Asian"],
      avgRating: 4.4,
      avgRatingString: "4.4",
      totalRatingsString: "9K+ ratings",
      veg: true,
      sla: { deliveryTime: 40, lastMileTravel: 3.1, slaString: "40 mins" },
      aggregatedDiscountInfoV3: { header: "40% OFF", subHeader: "UPTO ₹80" },
    },
  },
  {
    info: {
      id: "928164",
      name: "The Sandwich Shop",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/ba9f1f59-30d5-44de-afad-df6db8471ead_9648.jpg",
      locality: "Yeshwanthpur",
      areaName: "City Center",
      costForTwo: "₹300 for two",
      cuisines: ["Sandwiches", "Fast Food", "Continental"],
      avgRating: 4.8,
      avgRatingString: "4.8",
      totalRatingsString: "15K+ ratings",
      veg: true,
      sla: { deliveryTime: 24, lastMileTravel: 3.4, slaString: "24 mins" },
      aggregatedDiscountInfoV3: { header: "35% OFF", subHeader: "UPTO ₹70" },
    },
  },
  {
    info: {
      id: "491088",
      name: "Korean BBQ Grill",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/8/731001f1-f1c4-4f5f-849f-79a697cb0b72_390173.jpg",
      locality: "Banashankari",
      areaName: "East District",
      costForTwo: "₹550 for two",
      cuisines: ["Korean", "BBQ", "Asian"],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "11K+ ratings",
      veg: false,
      sla: { deliveryTime: 25, lastMileTravel: 4.9, slaString: "25 mins" },
      aggregatedDiscountInfoV3: { header: "60% OFF", subHeader: "UPTO ₹120" },
    },
  },
  {
    info: {
      id: "313884",
      name: "Cake Studio",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/17/7bd350a8-55e7-459b-83a2-e250e670d194_14558.JPG",
      locality: "Ulsoor",
      areaName: "West End",
      costForTwo: "₹800 for two",
      cuisines: ["Bakery", "Cakes", "Desserts"],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "4K+ ratings",
      veg: true,
      sla: { deliveryTime: 40, lastMileTravel: 2.1, slaString: "40 mins" },
      aggregatedDiscountInfoV3: { header: "25% OFF", subHeader: "UPTO ₹60" },
    },
  },
  {
    info: {
      id: "583295",
      name: "Rolls Royce Rolls",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/17/6def0f0f-9e6c-45c0-b5e6-05af750f27b5_795906.JPG",
      locality: "Frazer Town",
      areaName: "Uptown",
      costForTwo: "₹250 for two",
      cuisines: ["Street Food", "Rolls", "North Indian"],
      avgRating: 4.2,
      avgRatingString: "4.2",
      totalRatingsString: "14K+ ratings",
      veg: false,
      sla: { deliveryTime: 45, lastMileTravel: 1.6, slaString: "45 mins" },
      aggregatedDiscountInfoV3: { header: "40% OFF", subHeader: "UPTO ₹80" },
    },
  },
  {
    info: {
      id: "229034",
      name: "Naga Kitchen",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/acfcaacc-edf0-4189-8264-d614d312c0ee_740457.JPG",
      locality: "Sadashivanagar",
      areaName: "South Bangalore",
      costForTwo: "₹300 for two",
      cuisines: ["Naga", "North Eastern", "Spicy"],
      avgRating: 3.9,
      avgRatingString: "3.9",
      totalRatingsString: "14K+ ratings",
      veg: false,
      sla: { deliveryTime: 20, lastMileTravel: 3.0, slaString: "20 mins" },
      aggregatedDiscountInfoV3: { header: "45% OFF", subHeader: "UPTO ₹90" },
    },
  },
  {
    info: {
      id: "183852",
      name: "South Spice",
      cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
      locality: "Domlur",
      areaName: "Tech Hub",
      costForTwo: "₹700 for two",
      cuisines: ["South Indian", "Dosa", "Idli"],
      avgRating: 4.6,
      avgRatingString: "4.6",
      totalRatingsString: "22K+ ratings",
      veg: true,
      sla: { deliveryTime: 26, lastMileTravel: 1.4, slaString: "26 mins" },
      aggregatedDiscountInfoV3: { header: "25% OFF", subHeader: "UPTO ₹60" },
    },
  },
  {
    info: {
      id: "150930",
      name: "The Milkshake Bar",
      cloudinaryImageId: "rng/md/carousel/production/indian101",
      locality: "CV Raman Nagar",
      areaName: "North Zone",
      costForTwo: "₹450 for two",
      cuisines: ["Beverages", "Desserts", "Fast Food"],
      avgRating: 3.8,
      avgRatingString: "3.8",
      totalRatingsString: "22K+ ratings",
      veg: false,
      sla: { deliveryTime: 28, lastMileTravel: 5.0, slaString: "28 mins" },
      aggregatedDiscountInfoV3: { header: "60% OFF", subHeader: "UPTO ₹120" },
    },
  },
  {
    info: {
      id: "474500",
      name: "Punjabi Tadka",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/ba9f1f59-30d5-44de-afad-df6db8471ead_9648.jpg",
      locality: "MG Road",
      areaName: "Old City",
      costForTwo: "₹150 for two",
      cuisines: ["North Indian", "Punjabi", "Tandoor"],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "22K+ ratings",
      veg: false,
      sla: { deliveryTime: 21, lastMileTravel: 1.0, slaString: "21 mins" },
      aggregatedDiscountInfoV3: { header: "25% OFF", subHeader: "UPTO ₹60" },
    },
  },
  {
    info: {
      id: "952891",
      name: "Andhra Mess",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/8/731001f1-f1c4-4f5f-849f-79a697cb0b72_390173.jpg",
      locality: "Park Street",
      areaName: "New Town",
      costForTwo: "₹250 for two",
      cuisines: ["Andhra", "South Indian", "Spicy"],
      avgRating: 4.5,
      avgRatingString: "4.5",
      totalRatingsString: "16K+ ratings",
      veg: false,
      sla: { deliveryTime: 44, lastMileTravel: 2.0, slaString: "44 mins" },
      aggregatedDiscountInfoV3: { header: "10% OFF", subHeader: "UPTO ₹40" },
    },
  },
  {
    info: {
      id: "444513",
      name: "Burger Hub",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/17/7bd350a8-55e7-459b-83a2-e250e670d194_14558.JPG",
      locality: "Residency Road",
      areaName: "Suburban Belt",
      costForTwo: "₹300 for two",
      cuisines: ["Burgers", "American", "Fast Food"],
      avgRating: 3.9,
      avgRatingString: "3.9",
      totalRatingsString: "15K+ ratings",
      veg: false,
      sla: { deliveryTime: 28, lastMileTravel: 4.7, slaString: "28 mins" },
      aggregatedDiscountInfoV3: { header: "25% OFF", subHeader: "UPTO ₹60" },
    },
  },
  {
    info: {
      id: "313029",
      name: "Hyderabadi Biryani House",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/17/6def0f0f-9e6c-45c0-b5e6-05af750f27b5_795906.JPG",
      locality: "Brigade Road",
      areaName: "Metro Corridor",
      costForTwo: "₹700 for two",
      cuisines: ["Hyderabadi", "Biryani", "Mughlai"],
      avgRating: 3.8,
      avgRatingString: "3.8",
      totalRatingsString: "9K+ ratings",
      veg: false,
      sla: { deliveryTime: 22, lastMileTravel: 5.4, slaString: "22 mins" },
      aggregatedDiscountInfoV3: { header: "15% OFF", subHeader: "UPTO ₹150" },
    },
  },
  {
    info: {
      id: "104573",
      name: "Coastal Curry",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/acfcaacc-edf0-4189-8264-d614d312c0ee_740457.JPG",
      locality: "Commercial Street",
      areaName: "Riverside",
      costForTwo: "₹250 for two",
      cuisines: ["Kerala", "Seafood", "South Indian"],
      avgRating: 4.0,
      avgRatingString: "4.0",
      totalRatingsString: "4K+ ratings",
      veg: false,
      sla: { deliveryTime: 45, lastMileTravel: 1.0, slaString: "45 mins" },
      aggregatedDiscountInfoV3: { header: "20% OFF", subHeader: "UPTO ₹50" },
    },
  },
  {
    info: {
      id: "794262",
      name: "Chettinad Express",
      cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
      locality: "Lavelle Road",
      areaName: "Central District",
      costForTwo: "₹250 for two",
      cuisines: ["Chettinad", "South Indian", "Spicy"],
      avgRating: 4.3,
      avgRatingString: "4.3",
      totalRatingsString: "18K+ ratings",
      veg: false,
      sla: { deliveryTime: 20, lastMileTravel: 2.7, slaString: "20 mins" },
      aggregatedDiscountInfoV3: { header: "25% OFF", subHeader: "UPTO ₹60" },
    },
  },
  {
    info: {
      id: "763096",
      name: "Biryani Bhavan",
      cloudinaryImageId: "rng/md/carousel/production/indian101",
      locality: "Indiranagar",
      areaName: "Downtown",
      costForTwo: "₹500 for two",
      cuisines: ["Biryani", "Hyderabadi", "Mughlai"],
      avgRating: 4.5,
      avgRatingString: "4.5",
      totalRatingsString: "22K+ ratings",
      veg: false,
      sla: { deliveryTime: 20, lastMileTravel: 1.1, slaString: "20 mins" },
      aggregatedDiscountInfoV3: { header: "15% OFF", subHeader: "UPTO ₹150" },
    },
  },
  {
    info: {
      id: "139998",
      name: "Vietnamese Pho House",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/ba9f1f59-30d5-44de-afad-df6db8471ead_9648.jpg",
      locality: "Jayanagar",
      areaName: "South Zone",
      costForTwo: "₹400 for two",
      cuisines: ["Vietnamese", "Asian", "Soups"],
      avgRating: 4.8,
      avgRatingString: "4.8",
      totalRatingsString: "6K+ ratings",
      veg: false,
      sla: { deliveryTime: 18, lastMileTravel: 2.9, slaString: "18 mins" },
      aggregatedDiscountInfoV3: { header: "35% OFF", subHeader: "UPTO ₹70" },
    },
  },
  {
    info: {
      id: "948898",
      name: "Idli Dosa Point",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/8/731001f1-f1c4-4f5f-849f-79a697cb0b72_390173.jpg",
      locality: "Koramangala",
      areaName: "City Center",
      costForTwo: "₹900 for two",
      cuisines: ["South Indian", "Dosa", "Idli"],
      avgRating: 3.9,
      avgRatingString: "3.9",
      totalRatingsString: "5K+ ratings",
      veg: false,
      sla: { deliveryTime: 43, lastMileTravel: 3.3, slaString: "43 mins" },
      aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹75" },
    },
  },
  {
    info: {
      id: "789232",
      name: "Mumbai Chowpatty",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/17/7bd350a8-55e7-459b-83a2-e250e670d194_14558.JPG",
      locality: "Whitefield",
      areaName: "East District",
      costForTwo: "₹400 for two",
      cuisines: ["Street Food", "Maharashtrian", "Chaat"],
      avgRating: 4.5,
      avgRatingString: "4.5",
      totalRatingsString: "3K+ ratings",
      veg: false,
      sla: { deliveryTime: 26, lastMileTravel: 3.7, slaString: "26 mins" },
      aggregatedDiscountInfoV3: { header: "25% OFF", subHeader: "UPTO ₹60" },
    },
  },
  {
    info: {
      id: "797618",
      name: "Dessert Delight",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/17/6def0f0f-9e6c-45c0-b5e6-05af750f27b5_795906.JPG",
      locality: "HSR Layout",
      areaName: "West End",
      costForTwo: "₹250 for two",
      cuisines: ["Desserts", "Ice Cream", "Bakery"],
      avgRating: 4.3,
      avgRatingString: "4.3",
      totalRatingsString: "20K+ ratings",
      veg: true,
      sla: { deliveryTime: 18, lastMileTravel: 1.8, slaString: "18 mins" },
      aggregatedDiscountInfoV3: { header: "25% OFF", subHeader: "UPTO ₹60" },
    },
  },
  {
    info: {
      id: "847824",
      name: "Green Bites",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/acfcaacc-edf0-4189-8264-d614d312c0ee_740457.JPG",
      locality: "Electronic City",
      areaName: "Uptown",
      costForTwo: "₹400 for two",
      cuisines: ["Healthy Food", "Salads", "Vegan"],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "13K+ ratings",
      veg: false,
      sla: { deliveryTime: 31, lastMileTravel: 4.3, slaString: "31 mins" },
      aggregatedDiscountInfoV3: { header: "40% OFF", subHeader: "UPTO ₹80" },
    },
  },
  {
    info: {
      id: "121382",
      name: "Kebab Corner",
      cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
      locality: "Malleshwaram",
      areaName: "South Bangalore",
      costForTwo: "₹350 for two",
      cuisines: ["Mughlai", "Kebabs", "North Indian"],
      avgRating: 4.2,
      avgRatingString: "4.2",
      totalRatingsString: "13K+ ratings",
      veg: false,
      sla: { deliveryTime: 34, lastMileTravel: 5.3, slaString: "34 mins" },
      aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹75" },
    },
  },
  {
    info: {
      id: "407383",
      name: "Kolkata Kathi Rolls",
      cloudinaryImageId: "rng/md/carousel/production/indian101",
      locality: "Basavanagudi",
      areaName: "Tech Hub",
      costForTwo: "₹150 for two",
      cuisines: ["Rolls", "Street Food", "Bengali"],
      avgRating: 4.6,
      avgRatingString: "4.6",
      totalRatingsString: "5K+ ratings",
      veg: false,
      sla: { deliveryTime: 41, lastMileTravel: 4.9, slaString: "41 mins" },
      aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹75" },
    },
  },
  {
    info: {
      id: "713069",
      name: "The Pizza Oven",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/ba9f1f59-30d5-44de-afad-df6db8471ead_9648.jpg",
      locality: "Rajajinagar",
      areaName: "North Zone",
      costForTwo: "₹1000 for two",
      cuisines: ["Pizza", "Italian", "Fast Food"],
      avgRating: 4.7,
      avgRatingString: "4.7",
      totalRatingsString: "12K+ ratings",
      veg: false,
      sla: { deliveryTime: 39, lastMileTravel: 5.3, slaString: "39 mins" },
      aggregatedDiscountInfoV3: { header: "50% OFF", subHeader: "UPTO ₹100" },
    },
  },
  {
    info: {
      id: "945755",
      name: "Malabar Coast",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/8/731001f1-f1c4-4f5f-849f-79a697cb0b72_390173.jpg",
      locality: "Marathahalli",
      areaName: "Old City",
      costForTwo: "₹350 for two",
      cuisines: ["Kerala", "Seafood", "South Indian"],
      avgRating: 4.3,
      avgRatingString: "4.3",
      totalRatingsString: "25K+ ratings",
      veg: true,
      sla: { deliveryTime: 18, lastMileTravel: 5.0, slaString: "18 mins" },
      aggregatedDiscountInfoV3: { header: "35% OFF", subHeader: "UPTO ₹70" },
    },
  },
  {
    info: {
      id: "984732",
      name: "Chaat Street",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/17/7bd350a8-55e7-459b-83a2-e250e670d194_14558.JPG",
      locality: "BTM Layout",
      areaName: "New Town",
      costForTwo: "₹200 for two",
      cuisines: ["Street Food", "Chaat", "North Indian"],
      avgRating: 4.9,
      avgRatingString: "4.9",
      totalRatingsString: "11K+ ratings",
      veg: false,
      sla: { deliveryTime: 46, lastMileTravel: 4.8, slaString: "46 mins" },
      aggregatedDiscountInfoV3: { header: "10% OFF", subHeader: "UPTO ₹40" },
    },
  },
  {
    info: {
      id: "308615",
      name: "Sushi Station",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/17/6def0f0f-9e6c-45c0-b5e6-05af750f27b5_795906.JPG",
      locality: "JP Nagar",
      areaName: "Suburban Belt",
      costForTwo: "₹700 for two",
      cuisines: ["Japanese", "Sushi", "Asian"],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "3K+ ratings",
      veg: false,
      sla: { deliveryTime: 48, lastMileTravel: 1.3, slaString: "48 mins" },
      aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹75" },
    },
  },
  {
    info: {
      id: "379337",
      name: "The Bakery Box",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/acfcaacc-edf0-4189-8264-d614d312c0ee_740457.JPG",
      locality: "Yeshwanthpur",
      areaName: "Metro Corridor",
      costForTwo: "₹800 for two",
      cuisines: ["Bakery", "Cakes", "Desserts"],
      avgRating: 4.2,
      avgRatingString: "4.2",
      totalRatingsString: "7K+ ratings",
      veg: true,
      sla: { deliveryTime: 46, lastMileTravel: 3.8, slaString: "46 mins" },
      aggregatedDiscountInfoV3: { header: "30% OFF", subHeader: "UPTO ₹75" },
    },
  },
  {
    info: {
      id: "328867",
      name: "Chinese Dragon",
      cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
      locality: "Banashankari",
      areaName: "Riverside",
      costForTwo: "₹900 for two",
      cuisines: ["Chinese", "Asian", "Thai"],
      avgRating: 3.7,
      avgRatingString: "3.7",
      totalRatingsString: "16K+ ratings",
      veg: false,
      sla: { deliveryTime: 36, lastMileTravel: 1.9, slaString: "36 mins" },
      aggregatedDiscountInfoV3: { header: "15% OFF", subHeader: "UPTO ₹150" },
    },
  },
  {
    info: {
      id: "473457",
      name: "Spice Kingdom",
      cloudinaryImageId: "rng/md/carousel/production/indian101",
      locality: "Ulsoor",
      areaName: "Central District",
      costForTwo: "₹150 for two",
      cuisines: ["Indian", "North Indian", "Biryani"],
      avgRating: 4.4,
      avgRatingString: "4.4",
      totalRatingsString: "3K+ ratings",
      veg: false,
      sla: { deliveryTime: 28, lastMileTravel: 4.5, slaString: "28 mins" },
      aggregatedDiscountInfoV3: { header: "10% OFF", subHeader: "UPTO ₹40" },
    },
  },
  {
    info: {
      id: "215385",
      name: "Continental Kitchen",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/ba9f1f59-30d5-44de-afad-df6db8471ead_9648.jpg",
      locality: "Frazer Town",
      areaName: "Downtown",
      costForTwo: "₹150 for two",
      cuisines: ["Continental", "European", "Bakery"],
      avgRating: 4.4,
      avgRatingString: "4.4",
      totalRatingsString: "11K+ ratings",
      veg: false,
      sla: { deliveryTime: 35, lastMileTravel: 1.6, slaString: "35 mins" },
      aggregatedDiscountInfoV3: { header: "35% OFF", subHeader: "UPTO ₹70" },
    },
  },
  {
    info: {
      id: "336431",
      name: "The Bengali Kitchen",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/8/731001f1-f1c4-4f5f-849f-79a697cb0b72_390173.jpg",
      locality: "Sadashivanagar",
      areaName: "South Zone",
      costForTwo: "₹550 for two",
      cuisines: ["Bengali", "Indian", "Sweets"],
      avgRating: 3.9,
      avgRatingString: "3.9",
      totalRatingsString: "3K+ ratings",
      veg: true,
      sla: { deliveryTime: 29, lastMileTravel: 1.3, slaString: "29 mins" },
      aggregatedDiscountInfoV3: { header: "15% OFF", subHeader: "UPTO ₹150" },
    },
  },
  {
    info: {
      id: "739581",
      name: "Tandoori Nights",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/17/7bd350a8-55e7-459b-83a2-e250e670d194_14558.JPG",
      locality: "Domlur",
      areaName: "City Center",
      costForTwo: "₹350 for two",
      cuisines: ["Mughlai", "North Indian", "Kebabs"],
      avgRating: 4.0,
      avgRatingString: "4.0",
      totalRatingsString: "18K+ ratings",
      veg: false,
      sla: { deliveryTime: 33, lastMileTravel: 4.7, slaString: "33 mins" },
      aggregatedDiscountInfoV3: { header: "45% OFF", subHeader: "UPTO ₹90" },
    },
  },
  {
    info: {
      id: "746233",
      name: "Cafe Mocha",
      cloudinaryImageId: "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/17/6def0f0f-9e6c-45c0-b5e6-05af750f27b5_795906.JPG",
      locality: "CV Raman Nagar",
      areaName: "East District",
      costForTwo: "₹250 for two",
      cuisines: ["Cafe", "Beverages", "Snacks"],
      avgRating: 3.9,
      avgRatingString: "3.9",
      totalRatingsString: "9K+ ratings",
      veg: false,
      sla: { deliveryTime: 44, lastMileTravel: 2.7, slaString: "44 mins" },
      aggregatedDiscountInfoV3: { header: "25% OFF", subHeader: "UPTO ₹60" },
    },
  },
];